# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('hglasso_timesTwo', PACKAGE = 'hglasso', x)
}

BB_logistic <- function(R_X, R_A, R_rho) {
    .Call('hglasso_BB_logistic', PACKAGE = 'hglasso', R_X, R_A, R_rho)
}

